# Generated by Django 5.0.1 on 2024-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('match_name', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('match_time', models.TimeField()),
                ('match_location', models.CharField(max_length=100)),
                ('match_players', models.ManyToManyField(to='src.player')),
            ],
        ),
    ]
