# Generated by Django 5.0.2 on 2024-03-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
