# Generated by Django 5.0.2 on 2024-03-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_match_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
