# Generated by Django 5.0.2 on 2024-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_tournament_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='tournament_invites', to='src.player'),
        ),
    ]
