# Generated by Django 5.0.7 on 2024-07-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
